data=[{
    "id": 1,
    "first_name": "Cyndie",
    "last_name": "Doel",
    "email": "cdoel0@mashable.com",
    "gender": "Female",
    "ip_address": "238.5.229.159"
  }, {
    "id": 2,
    "first_name": "Oran",
    "last_name": "Bruyns",
    "email": "obruyns1@wsj.com",
    "gender": "Genderfluid",
    "ip_address": "191.32.240.69"
  }, {
    "id": 3,
    "first_name": "Elliot",
    "last_name": "Maxsted",
    "email": "emaxsted2@uiuc.edu",
    "gender": "Male",
    "ip_address": "167.194.16.55"
  }, {
    "id": 4,
    "first_name": "Alexis",
    "last_name": "Ferre",
    "email": "aferre3@reuters.com",
    "gender": "Male",
    "ip_address": "172.161.39.203"
  }, {
    "id": 5,
    "first_name": "Ancell",
    "last_name": "Standish",
    "email": "astandish4@apache.org",
    "gender": "Male",
    "ip_address": "8.219.24.5"
  }, {
    "id": 6,
    "first_name": "Nat",
    "last_name": "Tink",
    "email": "ntink5@icq.com",
    "gender": "Male",
    "ip_address": "65.146.234.235"
  }, {
    "id": 7,
    "first_name": "Codee",
    "last_name": "Balfour",
    "email": "cbalfour6@over-blog.com",
    "gender": "Female",
    "ip_address": "7.25.30.149"
  }, {
    "id": 8,
    "first_name": "Shena",
    "last_name": "Hartrick",
    "email": "shartrick7@sohu.com",
    "gender": "Female",
    "ip_address": "48.33.97.107"
  }, {
    "id": 9,
    "first_name": "Bentlee",
    "last_name": "Aucourte",
    "email": "baucourte8@chron.com",
    "gender": "Male",
    "ip_address": "188.51.205.26"
  }, {
    "id": 10,
    "first_name": "Adair",
    "last_name": "Tomaszek",
    "email": "atomaszek9@java.com",
    "gender": "Bigender",
    "ip_address": "99.52.22.38"
  }, {
    "id": 11,
    "first_name": "Alberik",
    "last_name": "Claibourn",
    "email": "aclaibourna@discuz.net",
    "gender": "Male",
    "ip_address": "255.126.80.35"
  }, {
    "id": 12,
    "first_name": "Letty",
    "last_name": "Aizikovitch",
    "email": "laizikovitchb@europa.eu",
    "gender": "Female",
    "ip_address": "60.121.0.117"
  }, {
    "id": 13,
    "first_name": "Juliet",
    "last_name": "Dinnis",
    "email": "jdinnisc@jimdo.com",
    "gender": "Female",
    "ip_address": "161.215.165.40"
  }, {
    "id": 14,
    "first_name": "Felecia",
    "last_name": "Tregunna",
    "email": "ftregunnad@naver.com",
    "gender": "Female",
    "ip_address": "178.165.62.230"
  }, {
    "id": 15,
    "first_name": "Sampson",
    "last_name": "Evesque",
    "email": "sevesquee@oaic.gov.au",
    "gender": "Male",
    "ip_address": "208.158.212.44"
  }, {
    "id": 16,
    "first_name": "Perri",
    "last_name": "Aleavy",
    "email": "paleavyf@google.de",
    "gender": "Polygender",
    "ip_address": "93.54.33.50"
  }, {
    "id": 17,
    "first_name": "Ana",
    "last_name": "Bengoechea",
    "email": "abengoecheag@squidoo.com",
    "gender": "Female",
    "ip_address": "183.96.56.121"
  }, {
    "id": 18,
    "first_name": "Caralie",
    "last_name": "Taylor",
    "email": "ctaylorh@businessweek.com",
    "gender": "Female",
    "ip_address": "199.93.229.14"
  }, {
    "id": 19,
    "first_name": "Ethelda",
    "last_name": "Ingilson",
    "email": "eingilsoni@jalbum.net",
    "gender": "Female",
    "ip_address": "73.61.218.153"
  }, {
    "id": 20,
    "first_name": "Dud",
    "last_name": "Perford",
    "email": "dperfordj@tiny.cc",
    "gender": "Male",
    "ip_address": "133.153.51.10"
  }]
  let arr=data.map((val)=>{
    return val.first_name;
  })
  let find='cy';
  arr.forEach(element => {
    if(element.toLowerCase().indexOf(find) > -1){
        console.log(element);
    }
  });